# For more information: https://laravel.com/
services:
    mensa.php.prod:
        container_name: mensa.php.prod
        pull_policy: always
        build: 
          dockerfile: Dockerfile.prod
        image: ghcr.io/vslcatena/mensa:prod
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        volumes: 
            - config:/var/www/html/conf.d
        networks:
            - net
        depends_on:
            - mensa.db
#        profiles:
#          - prod


    mensa.php:
        container_name: mensa.php
        pull_policy: missing
        build:
            context: ./vendor/laravel/sail/runtimes/${SAIL_VERSION:-8.1}
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: ghcr.io/vslcatena/mensa:sail-${SAIL_VERSION:-8.1}-app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        profiles:
          - dev
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - net
        depends_on:
            - mensa.db



    mensa.db:
        hostname: db
        container_name: mensa.db
        image: 'mariadb:10'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'db_data:/var/lib/mysql'
        networks:
            - net
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
  
    #phpmyadmin
    mensa.phpmyadmin:
        image: ghcr.io/linuxserver/phpmyadmin
        hostname: phpmyadmin
        container_name: mensa.phpmyadmin
        profiles:
          - dev
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: '${DB_PASSWORD}'
        ports:
          - "8181:80"
        networks:
          - net            
      
networks:
  net:
     driver: bridge
     ipam:
        driver: default
        config:
          - subnet: ${APP_NET_SUBNET:-192.168.8.224}/29
     driver_opts:
       com.docker.network.bridge.name: mensa_net
       
volumes:
    db_data:
        driver: local
    config:
        driver: local
