version: '3.8'

x-common-variables: &db_root_password
    'mensa'
#<<: *db_root_password
#MYSQL_ROOT_PASSWORD:*db_root_password

services:

  #ldap Service
  ldap:
    hostname: ${ADLDAP_CONTROLLERS}
    container_name: ldap
    image: 'osixia/openldap:latest'
    environment:
      LDAP_LOG_LEVEL: 256
      LDAP_DOMAIN: ${ADLDAP_CONTROLLERS}
      LDAP_ADMIN_PASSWORD: ${ADLDAP_ADMIN_PASSWORD}
      LDAP_CONFIG_PASSWORD: ${ADLDAP_ADMIN_PASSWORD}
      LDAP_BASE_DN: ${ADLDAP_BASEDN}
      LDAP_READONLY_USER: 'True'
      LDAP_READONLY_USER_USERNAME: ${ADLDAP_ADMIN_USERNAME}
      LDAP_READONLY_USER_PASSWORD: ${ADLDAP_ADMIN_PASSWORD}
      LDAP_RFC2307BIS_SCHEMA: 'True'
    command: --loglevel debug
    profiles:
      - testing
    networks:
      - net
    
  #MySQL Service
  db:
    hostname: db
    container_name: db
    image: 'yobasystems/alpine-mariadb:latest'
    environment:
      MYSQL_ROOT_PASSWORD: *db_root_password
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER:  ${DB_USERNAME}
      MYSQL_PASSWORD:  ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql/ # allows you to stop and restart the db service without losing data
      - ./etc/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - net

  #PHP Service
  app:
    hostname: app
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        WWW_UID: 1000 # $(id $USER -u) , default user laravel folder
        WWW_GID: 33 # can be kept on www-data (33)
    container_name: app
    depends_on:
      - db
    ports:
      - 1234:8080
    command: run #init, composer, artisan
    volumes:
      - "./etc/php/local.ini:/usr/local/etc/php/conf.d/local.ini"
      - .:/data/app:rw
    networks:
      - net
    
  #phpldapadmin Service
  phpldapadmin:
    hostname: phpldapadmin
    container_name: phpldapadmin
    profiles:
      - testing
    image: 'osixia/phpldapadmin:latest'
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'${ADLDAP_CONTROLLERS}': [{'server': [{'port': 389}]}, {'login': [{'bind_id': 'cn=admin,${ADLDAP_BASEDN}'}, {'bind_pass': '${ADLDAP_ADMIN_PASSWORD}'}, {'attr': 'cn'}, {'fallback_dn': True}]}]}]"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - 8081:80
    networks:
      - net  
    
  #phpmyadmin
  phpmyadmin:
    image: ghcr.io/linuxserver/phpmyadmin
    hostname: phpmyadmin
    container_name: phpmyadmin
    profiles:
      - testing
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_USER: root
      PMA_PASSWORD: *db_root_password
    ports:
      - "8082:80"
    networks:
      - net



#Docker Networks
networks:
  net:
    driver: bridge
volumes:
  dbdata:
    driver: local