version: '3.9'
services:
    database:
      image: 'mariadb:10'
      ports:
          - '3306:3306'
      environment:
        MYSQL_ROOT_PASSWORD: rootpwd
        MYSQL_DATABASE: mydatabase
        MYSQL_USER: user
        MYSQL_PASSWORD: pwd
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        timeout: 5s
        retries: 3
      networks:
        - mensa
    api:
      image: 'node:20-alpine'
      ports:
        - 3000:3000
      working_dir: /home/node/app
      volumes:
        - ../api:/home/node/app
      command: "npm run start:dev"
      networks:
        - mensa
      depends_on:
        database:
          condition: service_healthy
          required: true
    web:
      build:
        context: .
        dockerfile: Dockerfile.web.dev
      ports:
        - 4200:4200
      working_dir: /home/node/app
      volumes:
        - ../web:/home/node/app
      command: "npm run start"
      networks:
        - mensa
networks:
  mensa: