version: '3.9'
services:
    api:
      build:
        context: .
        dockerfile: Dockerfile.install
      container_name: api_npm_install
      working_dir: /home/node/app
      volumes:
        - ../api:/home/node/app
      command: "npm install"
    web:
      build:
        context: .
        dockerfile: Dockerfile.install
      container_name: web_npm_install
      working_dir: /home/node/app
      volumes:
        - ../web:/home/node/app
      command: "npm install"